[package]
name = "cueball"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.2.7"
bitbybit = "1.3.2"
byteorder = "1.5.0"
bytes = "1.6.0"
hex = "0.4.3"
num-traits = "0.2"
num-derive = "0.4"